name = "cobra"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# WAJIB! Supaya wrangler tidak memanggil /memberships lagi
account_id = "7431e1cb1076e540960f6796b8971a49"

# KV Namespace untuk UI (public/)
[[kv_namespaces]]
binding = "Pages2"
id = "ed173527174742cb9b0180fbd21d0611"   # sudah benar

# Public directory (untuk GitHub Actions upload file ke KV)
[site]
bucket = "./public"

# ENV yang tidak sensitive â€” masukkan nilai aslinya (atau kosongkan dulu)
[vars]
BASE_API_URL = "https://api.myxl.xlaxiata.co.id"
BASE_CIAM_URL = "https://gede.ciam.xlaxiata.co.id"
UA = "myXL / 8.9.0(1202); com.android.vending; (samsung; SM-N935F; SDK 33; Android 13)"

# Secret disimpan lewat Cloudflare Dashboard:
# API_KEY
# BASIC_AUTH
# AES_KEY_ASCII
# ENCRYPTED_FIELD_KEY
# AX_FP_KEY
# XDATA_KEY
# AX_API_SIG_KEY
# X_API_BASE_SECRET
# CIRCLE_MSISDN_KEY
