
name = "cobra"
main = "worker.js"
account_id = "7431e1cb1076e540960f6796b8971a49"
workers_dev = true
compatibility_date = "2025-11-26"

# existing KV for users
kv_namespaces = [
  { binding = "Cobra", id = "b151ed8e49234d568df5e2d9e524e4dc" },
  { binding = "Pages2", id = "ed173527174742cb9b0180fbd21d0611" }
]
